# -*- mode: python ; coding: utf-8 -*-

from pathlib import Path

block_cipher = None

dist_dir = Path('.') / 'dist'
work_dir = Path('.') / 'build_pyi'

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('database', 'database'),
    ],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'PySide6.QtSql',
        'sqlite3',
        'database.connection',
        'database.repositories.base_repository',
        'database.repositories.alert_repository',
        'database.repositories.event_repository',
        'database.repositories.project_repository',
        'database.repositories.task_repository',
        'database.repositories.knowledge_page_repository',
        'database.repositories.attachment_repository',
        'database.repositories.entity_link_repository',
        'database.repositories.activity_log_repository',
        'database.repositories.note_repository',
        'database.repositories.idea_repository',
        'database.repositories.agenda_repository',
        'database.repositories.task_dependency_repository',
        'services.alert_service',
        'services.event_service',
        'services.project_service',
        'services.task_service',
        'services.knowledge_page_service',
        'services.attachment_service',
        'services.link_service',
        'services.note_service',
        'services.idea_service',
        'services.agenda_service',
        'services.search_service',
        'services.smart_capture_service',
        'core.snapshot_worker',
        'gui.theme',
        'gui.main_window_qt',
        'gui.views.agenda_qt',
        'gui.views.wiki_qt',
        'gui.views.projects_qt',
        'gui.views.tasks_qt',
        'gui.views.task_detail_qt',
        'gui.views.project_360_qt',
        'gui.views.activity_summary_qt',
        'gui.views.ideas_qt',
        'gui.views.notes_qt',
        'gui.views.workbench_qt',
        'gui.dialogs_qt.project_dialog_qt',
        'gui.dialogs_qt.task_dialog_qt',
        'gui.dialogs_qt.event_dialog_qt',
        'gui.dialogs_qt.schedule_dialog_qt',
        'gui.dialogs_qt.alarm_dialog_qt',
        'gui.dialogs_qt.alarm_popup_qt',
        'gui.dialogs_qt.reference_warning_dialog_qt',
        'gui.dialogs_qt.idea_dialog_qt',
        'gui.dialogs_qt.promote_idea_dialog_qt',
        'gui.components.alarm_cards_qt',
        'gui.components.alarm_tree_qt',
        'gui.components.agenda_tree_qt',
        'gui.components.page_header',
        'gui.components.metric_card_qt',
        'gui.components.badge_delegate',
        'gui.components.card',
        'gui.components.drag_drop_table_qt',
        'gui.components.indicator_card',
        'gui.components.references_panel_qt',
        'gui.components.progress_bar',
        'gui.components.badge',
        'gui.components.buttons',
        'gui.widgets.wiki_text_edit',
        'core.error_handler',
        'core.event_bus',
        'core.snapshot_worker',
        'core.background_queue',
        'core.data_context',
        'core.startup',
        'models.entities',
        'models.alert',
        'models.note',
        'models.idea',
        'models.agenda_item',
        'models.task_dependency',
        'models.user_capacity',
        'utils.paths',
        'utils.instrumentation',
        'utils.autocomplete',
        'utils.dropdown_autocomplete',
        'utils.wiki_parser',
    ],
    hookspath=[],
    hooksconfig={},
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'PIL',
        'PIL.Image',
        'PIL.ImageQt',
        'cv2',
        'scipy',
        'pandas',
        'notebook',
        'jupyter',
        'IPython',
        'setuptools',
        'pip',
        'pkg_resources',
        'cffi',
        'cryptography',
    ],
    runtime_hooks=[],
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name='CentralDeGestao',
    debug=False,
    strip=False,
    upx=False,
    runtime_tmpdir=None,
    console=False,
    icon='app.ico',
)
