ALTER TABLE projects ADD COLUMN due_date DATETIME;
ALTER TABLE projects ADD COLUMN alert_date DATETIME;
ALTER TABLE tasks ADD COLUMN alert_date DATETIME;
ALTER TABLE ideas ADD COLUMN next_review_date DATETIME;
ALTER TABLE notes ADD COLUMN project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL;
